---
# RuboCop tool configuration used by rake lint:style command.
AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Max: 99

Metrics/ClassLength:
  Max: 200

Style/NumericLiterals:
  Enabled: false
...
